// AUTO-GENERATED from forge artifacts (packages/contracts/out). Do not edit by hand.
// Regenerate after changing the contracts.
export const spendPolicyFactoryAbi = [
  { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'createAccount',
    inputs: [
      { name: 'userSalt', type: 'bytes32', internalType: 'bytes32' },
      {
        name: 'p',
        type: 'tuple',
        internalType: 'struct SpendPolicyFactory.InitParams',
        components: [
          { name: 'token', type: 'address', internalType: 'contract IERC20' },
          { name: 'owner', type: 'address', internalType: 'address' },
          { name: 'cosigner', type: 'address', internalType: 'address' },
          { name: 'vault', type: 'address', internalType: 'address' },
          { name: 'target', type: 'address', internalType: 'address' },
          { name: 'maxAmount', type: 'uint256', internalType: 'uint256' },
          { name: 'expiry', type: 'uint40', internalType: 'uint40' },
          { name: 'interval', type: 'uint40', internalType: 'uint40' },
          { name: 'mode', type: 'uint8', internalType: 'enum SpendPolicyAccount.Mode' },
        ],
      },
    ],
    outputs: [{ name: 'account', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'implementation',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'predictAddress',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'userSalt', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'AccountCreated',
    inputs: [
      { name: 'account', type: 'address', indexed: true, internalType: 'address' },
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'target', type: 'address', indexed: true, internalType: 'address' },
      { name: 'maxAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'salt', type: 'bytes32', indexed: false, internalType: 'bytes32' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'FailedDeployment', inputs: [] },
  {
    type: 'error',
    name: 'InsufficientBalance',
    inputs: [
      { name: 'balance', type: 'uint256', internalType: 'uint256' },
      { name: 'needed', type: 'uint256', internalType: 'uint256' },
    ],
  },
] as const;

export const spendPolicyAccountAbi = [
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    name: 'actionDigest',
    inputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'cosigner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'expiry',
    inputs: [],
    outputs: [{ name: '', type: 'uint40', internalType: 'uint40' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'init',
    inputs: [
      { name: 'token_', type: 'address', internalType: 'contract IERC20' },
      { name: 'owner_', type: 'address', internalType: 'address' },
      { name: 'cosigner_', type: 'address', internalType: 'address' },
      { name: 'vault_', type: 'address', internalType: 'address' },
      { name: 'target_', type: 'address', internalType: 'address' },
      { name: 'maxAmount_', type: 'uint256', internalType: 'uint256' },
      { name: 'expiry_', type: 'uint40', internalType: 'uint40' },
      { name: 'interval_', type: 'uint40', internalType: 'uint40' },
      { name: 'mode_', type: 'uint8', internalType: 'enum SpendPolicyAccount.Mode' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'interval',
    inputs: [],
    outputs: [{ name: '', type: 'uint40', internalType: 'uint40' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lastPull',
    inputs: [],
    outputs: [{ name: '', type: 'uint40', internalType: 'uint40' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxAmount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'mode',
    inputs: [],
    outputs: [{ name: '', type: 'uint8', internalType: 'enum SpendPolicyAccount.Mode' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nonce',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pay',
    inputs: [
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'ownerSig', type: 'bytes', internalType: 'bytes' },
      { name: 'cosignerSig', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pull',
    inputs: [
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'cosignerSig', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'remaining',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'spent',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'sweepDigest',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'sweepExpired',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'sweepToVault',
    inputs: [{ name: 'ownerSig', type: 'bytes', internalType: 'bytes' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'target',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'token',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'vault',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'target', type: 'address', indexed: true, internalType: 'address' },
      { name: 'maxAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'expiry', type: 'uint40', indexed: false, internalType: 'uint40' },
      { name: 'mode', type: 'uint8', indexed: false, internalType: 'enum SpendPolicyAccount.Mode' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Paid',
    inputs: [
      { name: 'target', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'spent', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Pulled',
    inputs: [
      { name: 'target', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'spent', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SweptToVault',
    inputs: [
      { name: 'vault', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'AlreadyInitialized', inputs: [] },
  { type: 'error', name: 'BadCosignerSig', inputs: [] },
  { type: 'error', name: 'BadOwnerSig', inputs: [] },
  { type: 'error', name: 'ECDSAInvalidSignature', inputs: [] },
  {
    type: 'error',
    name: 'ECDSAInvalidSignatureLength',
    inputs: [{ name: 'length', type: 'uint256', internalType: 'uint256' }],
  },
  {
    type: 'error',
    name: 'ECDSAInvalidSignatureS',
    inputs: [{ name: 's', type: 'bytes32', internalType: 'bytes32' }],
  },
  { type: 'error', name: 'Expired', inputs: [] },
  { type: 'error', name: 'NotExpiredYet', inputs: [] },
  { type: 'error', name: 'OverLimit', inputs: [] },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'TooSoon', inputs: [] },
  { type: 'error', name: 'WrongMode', inputs: [] },
  { type: 'error', name: 'ZeroAddress', inputs: [] },
  { type: 'error', name: 'ZeroAmount', inputs: [] },
] as const;

export const vaultAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'token_', type: 'address', internalType: 'contract IERC20' },
      { name: 'owner_', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    name: 'balance',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'deposit',
    inputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'fundAccount',
    inputs: [
      { name: 'account', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'token',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'AccountFunded',
    inputs: [
      { name: 'account', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Deposited',
    inputs: [
      { name: 'from', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Withdrawn',
    inputs: [
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'NotOwner', inputs: [] },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'ZeroAddress', inputs: [] },
  { type: 'error', name: 'ZeroAmount', inputs: [] },
] as const;
