/**
 * withCertPinning — TLS certificate (SPKI public-key) pinning for the native app.
 *
 * Pins the two hosts the app trusts with funds-relevant traffic:
 *   - api.ctrlarcz.xyz         (the co-signer / bridge / gasless backend)
 *   - rpc.testnet.arc.network  (the Arc JSON-RPC the wallet reads from)
 *
 * We pin the SPKI hashes of the *Let's Encrypt roots* (ISRG Root X1 + X2) plus the
 * current issuing intermediates. Pinning the roots (not the 90-day leaf) means the
 * pin survives normal certificate rotation while still rejecting a certificate from
 * any other CA — the exact threat pinning exists for (a mis-issued / rogue-CA cert
 * used to MITM the co-signer). The extra intermediate pins tighten it to the two
 * intermediates actually in use today.
 *
 * This is enforced by the OS TLS stack, so it covers every connection the app makes
 * to these hosts (fetch to the backend and every viem RPC call), not just app-level
 * fetches. It takes effect in a native build (EAS / prebuild); Expo Go cannot pin.
 *
 * The Android pin-set carries an `expiration` so a forgotten pin can never brick the
 * app in the field: past that date the OS ignores the pin-set and falls back to the
 * normal trust store. Rotate the pins (and this date) well before it.
 */
const {
  withAndroidManifest,
  withDangerousMod,
  withInfoPlist,
  AndroidConfig,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// SPKI SHA-256 pins (base64). Roots are long-lived; intermediates rotate slowly.
const ISRG_ROOT_X1 = 'C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=';
const ISRG_ROOT_X2 = 'diGVwiVYbubAI3RW4hB9xU8e/CH2GnkuvVFZE8zmgzI=';
const LE_YE1 = 'brzvtCELCIZUo4sD/qPX0ccRtPsd3DY6RfmxpOU9oB4='; // api.ctrlarcz.xyz issuer
const LE_R12 = 'kZwN96eHtZftBWrOZUsd6cA4es80n3NzSk/XtYz2EqQ='; // rpc.testnet.arc.network issuer

const PINS = [ISRG_ROOT_X1, ISRG_ROOT_X2, LE_YE1, LE_R12];
const DOMAINS = ['api.ctrlarcz.xyz', 'rpc.testnet.arc.network'];
const PIN_EXPIRATION = '2027-06-01'; // safety valve; rotate pins before this

const ANDROID_NSC = 'network_security_config';

function androidXml() {
  const pinEls = PINS.map((p) => `        <pin digest="SHA-256">${p}</pin>`).join('\n');
  const domainBlocks = DOMAINS.map(
    (d) => `    <domain-config>
      <domain includeSubdomains="false">${d}</domain>
      <pin-set expiration="${PIN_EXPIRATION}">
${pinEls}
      </pin-set>
    </domain-config>`,
  ).join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withCertPinning.js. Do not edit by hand. -->
<network-security-config>
${domainBlocks}
</network-security-config>
`;
}

function withAndroidCertPinningXml(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const res = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(res, { recursive: true });
      fs.writeFileSync(path.join(res, `${ANDROID_NSC}.xml`), androidXml(), 'utf8');
      return cfg;
    },
  ]);
}

function withAndroidCertPinningManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.$['android:networkSecurityConfig'] = `@xml/${ANDROID_NSC}`;
    return cfg;
  });
}

function withIosCertPinning(config) {
  return withInfoPlist(config, (cfg) => {
    const ats = cfg.modResults.NSAppTransportSecurity || {};
    const pinned = {};
    for (const d of DOMAINS) {
      pinned[d] = {
        NSIncludesSubdomains: false,
        NSPinnedCAIdentities: PINS.map((p) => ({ 'SPKI-SHA256-BASE64': p })),
      };
    }
    ats.NSPinnedDomains = pinned;
    cfg.modResults.NSAppTransportSecurity = ats;
    return cfg;
  });
}

module.exports = function withCertPinning(config) {
  config = withAndroidCertPinningXml(config);
  config = withAndroidCertPinningManifest(config);
  config = withIosCertPinning(config);
  return config;
};
