/**
 * withCertPinning — TLS certificate (SPKI public-key) pinning for the native app.
 *
 * Pins the two hosts the app trusts with funds-relevant traffic:
 *   - api.ctrlarcz.xyz         (the co-signer / bridge / gasless backend)
 *   - rpc.testnet.arc.network  (the Arc JSON-RPC the wallet reads from)
 *
 * We pin the SPKI hashes of the current *Let's Encrypt issuing intermediates* (YE1
 * for the API, R12 for the RPC), NOT the shared ISRG roots and NOT the 90-day leaf:
 *   - Pinning the leaf would break on every ~90-day renewal (impractical for an app
 *     that ships through store review).
 *   - Pinning the ISRG *root* would accept ANY Let's Encrypt certificate for these
 *     hosts — that is CA-level pinning, which barely narrows the trust set.
 *   - Pinning the issuing *intermediate* is the durable middle ground: it survives
 *     leaf rotation but rejects a certificate issued by a DIFFERENT CA — the common
 *     rogue-CA / mis-issuance MITM. Both intermediates are pinned on both hosts so a
 *     cross-issuer renewal does not brick the app.
 *
 * Residual, stated honestly: this does NOT defend against Let's Encrypt itself
 * mis-issuing under a pinned intermediate. That residual is covered at a different
 * layer — the funds-critical co-signer ADDRESS is pinned in-app (EXPECTED_COSIGNER)
 * and enforced on-chain, so even a successful TLS MITM cannot forge a spend.
 *
 * Enforced by the OS TLS stack, so it covers every backend fetch and every viem RPC
 * call, not just app-level fetches. Takes effect in a native (EAS) build; Expo Go
 * cannot pin. The Android pin-set carries an `expiration` backstop so a missed pin
 * rotation degrades to the system trust store rather than bricking the app in the
 * field (iOS has no equivalent knob, so on iOS the pins are hard until an app
 * update). Rotate the pins and this date before Let's Encrypt retires YE1/R12.
 */
const {
  withAndroidManifest,
  withDangerousMod,
  withInfoPlist,
  AndroidConfig,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// SPKI SHA-256 pins (base64) of the current Let's Encrypt issuing intermediates.
const LE_YE1 = 'brzvtCELCIZUo4sD/qPX0ccRtPsd3DY6RfmxpOU9oB4='; // api.ctrlarcz.xyz issuer
const LE_R12 = 'kZwN96eHtZftBWrOZUsd6cA4es80n3NzSk/XtYz2EqQ='; // rpc.testnet.arc.network issuer

// Both intermediates on both hosts: rejects any non-Let's-Encrypt CA while tolerating
// a cross-issuer renewal (YE1<->R12) without bricking.
const PINS = [LE_YE1, LE_R12];
const DOMAINS = ['api.ctrlarcz.xyz', 'rpc.testnet.arc.network'];
const PIN_EXPIRATION = '2027-06-01'; // Android backstop; rotate pins before this

const ANDROID_NSC = 'network_security_config';

function androidXml() {
  const pinEls = PINS.map((p) => `        <pin digest="SHA-256">${p}</pin>`).join('\n');
  const domainBlocks = DOMAINS.map(
    (d) => `    <domain-config>
      <domain includeSubdomains="false">${d}</domain>
      <pin-set expiration="${PIN_EXPIRATION}">
${pinEls}
      </pin-set>
    </domain-config>`,
  ).join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withCertPinning.js. Do not edit by hand. -->
<network-security-config>
${domainBlocks}
</network-security-config>
`;
}

function withAndroidCertPinningXml(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const res = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(res, { recursive: true });
      fs.writeFileSync(path.join(res, `${ANDROID_NSC}.xml`), androidXml(), 'utf8');
      return cfg;
    },
  ]);
}

function withAndroidCertPinningManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.$['android:networkSecurityConfig'] = `@xml/${ANDROID_NSC}`;
    return cfg;
  });
}

function withIosCertPinning(config) {
  return withInfoPlist(config, (cfg) => {
    const ats = cfg.modResults.NSAppTransportSecurity || {};
    const pinned = {};
    for (const d of DOMAINS) {
      pinned[d] = {
        NSIncludesSubdomains: false,
        NSPinnedCAIdentities: PINS.map((p) => ({ 'SPKI-SHA256-BASE64': p })),
      };
    }
    ats.NSPinnedDomains = pinned;
    cfg.modResults.NSAppTransportSecurity = ats;
    return cfg;
  });
}

module.exports = function withCertPinning(config) {
  config = withAndroidCertPinningXml(config);
  config = withAndroidCertPinningManifest(config);
  config = withIosCertPinning(config);
  return config;
};
